name: learn-github-actions
on: [push]
jobs:
  container-test-job:
    runs-on: self-hosted 
    container: condaforge/miniforge3
    steps:
      - name: Check for python version 
        run: python --version 

